[
:gr_setcallback
:gr_initgr
:gr_opengks
:gr_closegks
:gr_inqdspsize
:gr_openws
:gr_closews
:gr_activatews
:gr_deactivatews
:gr_clearws
:gr_updatews
:gr_polyline
:gr_polymarker
:gr_text
:gr_inqtext
:gr_textx
:gr_inqtextx
:gr_fillarea
:gr_cellarray
:gr_nonuniformcellarray
:gr_polarcellarray
:gr_nonuniformpolarcellarray
:gr_gdp
:gr_path
:gr_spline
:gr_gridit
:gr_setlinetype
:gr_setlinewidth
:gr_setlinecolorind
:gr_setmarkertype
:gr_setmarkersize
:gr_setmarkercolorind
:gr_settextfontprec
:gr_setcharexpan
:gr_setcharspace
:gr_settextcolorind
:gr_setcharheight
:gr_inqcharheight
:gr_setcharup
:gr_settextpath
:gr_settextalign
:gr_setfillintstyle
:gr_setfillstyle
:gr_setfillcolorind
:gr_setcolorrep
:gr_setscale
:gr_inqscale
:gr_setwindow
:gr_inqwindow
:gr_setviewport
:gr_inqviewport
:gr_selntran
:gr_setclip
:gr_setwswindow
:gr_setwsviewport
:gr_createseg
:gr_copysegws
:gr_redrawsegws
:gr_setsegtran
:gr_closeseg
:gr_samplelocator
:gr_emergencyclosegks
:gr_updategks
:gr_setspace
:gr_textext
:gr_inqtextext
:gr_axes
:gr_axeslbl
:gr_grid
:gr_grid3d
:gr_verrorbars
:gr_herrorbars
:gr_polyline3d
:gr_polymarker3d
:gr_axes3d
:gr_settitles3d
:gr_titles3d
:gr_surface
:gr_contour
:gr_contourf
:gr_hexbin
:gr_setcolormap
:gr_colorbar
:gr_inqcolor
:gr_inqcolorfromrgb
:gr_hsvtorgb
:gr_tick
:gr_validaterange
:gr_adjustlimits
:gr_adjustrange
:gr_beginprint
:gr_beginprintext
:gr_endprint
:gr_ndctowc
:gr_wctondc
:gr_wc3towc
:gr_drawrect
:gr_fillrect
:gr_drawarc
:gr_fillarc
:gr_drawpath
:gr_setarrowstyle
:gr_setarrowsize
:gr_drawarrow
:gr_readimage
:gr_drawimage
:gr_importgraphics
:gr_setshadow
:gr_settransparency
:gr_setcoordxform
:gr_begingraphics
:gr_endgraphics
:gr_getgraphics
:gr_drawgraphics
:gr_startlistener
:gr_mathtex
:gr_inqmathtex
:gr_setregenflags
:gr_inqregenflags
:gr_savestate
:gr_restorestate
:gr_selectcontext
:gr_destroycontext
:gr_uselinespec
:gr_delaunay
:gr_interp2
:gr_trisurface
:gr_tricontour
:gr_gradient
:gr_quiver
:gr_reducepoints
:gr_version
:gr_shadepoints
:gr_shadelines
:gr_setcolormapfromrgb
:gr_panzoom
:gr_setborderwidth
:gr_setbordercolorind
:gr_setprojectiontype
:gr_setperspectiveprojection
:gr_setorthographicprojection
:gr_settransformationparameters
:gr_setresamplemethod
:gr_setwindow3d
:gr_setspace3d
:gr_text3d
:gr_inqtext3d
:gr_settextencoding
:gr_inqtextencoding
:gr_loadfont
:gr_inqvpsize
:gr_setpicturesizeforvolume
:gr_inqtransformationparameters
:gr_polygonmesh3d
:gr_setscientificformat
:gr_setresizebehaviour
:gr_inqprojectiontype
:gr_beginselection
:gr_endselection
:gr_moveselection
:gr_setmathfont
:gr_inqmathfont
:gr_setclipregion
:gr_inqclipregion
]
